---
title: "Simulation Package"
author: "Zach Samach"
date: '2022-06-05'
output: word_document
---

```{r}
install.packages("lubridate")
install.packages("fitdistrplus")
install.packages("logspline")

install.packages("MonteCarlo")
install.packages("ExtDist")
install.packages("fixest")
```



```{r}
library(tidyverse)
library(reticulate)
library(readxl)
library(reticulate)
library(ExtDist)
library(simhelpers)
library(dplyr)
library(tibble)
library(purrr)
library(tidyr)
library(knitr)
library(kableExtra)
library(broom)
library(ggplot2)
```




```{r}  
#https://fred.stlouisfed.org/tags/series?t=inflation
inflation <- read_csv("FPCPITOTLZGUSA.csv")
inflation$DATE<-as.Date(inflation$DATE)



#https://fred.stlouisfed.org/series/NFCI

shadow_rate <- read_csv("NFCI.csv")

shadow_rate<-aggregate(shadow_rate$NFCI, list(format(shadow_rate$DATE, "%Y-%m-%1")), mean)

colnames(shadow_rate)[colnames(shadow_rate) == 'Group.1']<- 'DATE'

colnames(shadow_rate)[colnames(shadow_rate) == 'x']<- 'NFCI'



shadow_rate$DATE <- as.Date(shadow_rate$DATE, format = "%Y-%m-%d")




#https://fred.stlouisfed.org/series/FEDFUNDS

FEDFUNDS <- read_csv("FEDFUNDS.csv")

FEDFUNDS$DATE<-as.Date(FEDFUNDS$DATE)




```

```{r}
composite <- left_join(inflation,shadow_rate, by=c("DATE"))

composite <- left_join(composite,FEDFUNDS, by=c("DATE"))

composite <- left_join(composite,M_supply, by=c("DATE"))

composite<-composite %>% drop_na()

```


```{r}
#find distribution for simulation

library(fitdistrplus)
library(logspline)

descdist(composite$FPCPITOTLZGUSA, discrete = FALSE)

```


```{r}
est.par <- eBeta(X=composite$FPCPITOTLZGUSA)
est.par
```

```{r}
#find distribution for simulation

library(fitdistrplus)
library(logspline)

descdist(composite$M1REAL, discrete = FALSE)

```



```{r}
descdist(composite$NFCI, discrete = FALSE)
```


```{r}
est.par <- eBeta(X=composite$NFCI)
est.par
```


```{r}
descdist(composite$FEDFUNDS, discrete = FALSE)
```

```{r}
est.par2 <- eGamma(composite$FEDFUNDS)
est.par2
```




```{r}
ggplot(composite, aes(x = composite$FPCPITOTLZGUSA)) + 
  geom_density(alpha = .5) + 
  labs(x = "Rate", y = "Density") + 
  theme_bw() +
  theme(legend.position = c(0.9, 0.8))
```
```{r}
ggplot(composite, aes(x = composite$NFCI)) + 
  geom_density(alpha = .5) + 
  labs(x = "Rate", y = "Density") + 
  theme_bw() +
  theme(legend.position = c(0.9, 0.8))
```

```{r}
ggplot(composite, aes(x = composite$FEDFUNDS)) + 
  geom_density(alpha = .5) + 
  labs(x = "Rate", y = "Density") + 
  theme_bw() +
  theme(legend.position = c(0.9, 0.8))
```




```{r}
model <- lm(FPCPITOTLZGUSA ~ log(NFCI)+log(FEDFUNDS), data=composite)

summary(model)
```
`
```{r}
sd(coef(summary(model))[, "Std. Error"])
sd(coef(summary(model))[, "Estimate"])
```


```{r}
Y<-function(n,loc,scale){
  # generate sample:
    U_i <- rnorm(n, 0.6388523, 0.4178944) # Error
    X_i_1 <- rbeta(n,1.05910004,0.02634973) # First independent variable (n,shape1, shape2)
    X_i_2 <- rgamma(n,1.4698743,1/0.2997944)# second independent variable (n,shape, scale)
    Y <- (2.2875 + 1.2890 *X_i_1 + 2.4787*X_i_2 + U_i)  # Dependent variable with coeffecients
    
  # calculate test statistic:
    stat<-sqrt(n)*mean(Y)/sd(Y)
    
  # get test decision:
      decision<-abs(stat)>2.58
  # return result:
    return(list("decision"=decision, "stat"=stat,"Inlfation"=mean(Y)))
}
```



```{r}
n=10
U_i <- rnorm(n, mean(0.50655,0.39056,0.08632), 0.2170288) # Error
X_i_1 <- rbeta(n,1.05910004,0.02634973) # First independent variable (n,shape1, shape2)
X_i_2 <- rgamma(n,1.4698743,1/0.2997944)
```


```{r}
n_grid<-c(5,10,15)

loc_grid<-c(mean(X_i_1),mean(X_i_2),mean(U_i))
scale_grid<-c(sd(X_i_1),sd(X_i_2),sd(U_i))
param_list=list("n"=n_grid, "loc"=loc_grid, "scale"=scale_grid)

```


```{r}
library(MonteCarlo)
MC_result<-MonteCarlo(func=Y, nrep=10000, param_list=param_list)
```


```{r}
df<-MakeFrame(MC_result)
df
```


